project_id = "tdykegnmomyyucbhslok"

[auth]
enable_confirmations = false

[functions.verify-time-slot]
verify_jwt = false

[functions.send-order-notification]
verify_jwt = false

[functions.notify-order-delay]
verify_jwt = false

[functions.test-email]
verify_jwt = false

# Stripe webhook must be public (signature is verified inside the function)
[functions.webhook-stripe]
verify_jwt = false

# SMS notification function must be public
[functions.send-sms-notification]
verify_jwt = false

# Restaurant alert function must be public
[functions.send-restaurant-alert]
verify_jwt = false
