
project_id = "tdykegnmomyyucbhslok"

[auth]
enable_confirmations = false

[functions.send-order-notification]
verify_jwt = false

[functions.test-email-simple]
verify_jwt = false

[functions.debug-brevo]
verify_jwt = false

[functions.notify-order-delay]
verify_jwt = false
